--- @type vim.lsp.Config
return {
    filetypes = {
        'astro',
        'astro-markdown',
        'ejs',
        'eta',
        'gohtml',
        'gohtmltmpl',
        'handlebars',
        'hbs',
        'htmlangular',
        'css',
        'less',
        'postcss',
        'sass',
        'scss',
        'javascript',
        'javascriptreact',
        'typescript',
        'typescriptreact',
        'vue',
        'svelte',
        'templ',
    },
}
